import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const launcher = readFileSync(new URL('../scripts/start-desktop.ps1', import.meta.url), 'utf8');
const shortcut = readFileSync(new URL('../scripts/install-shortcut.ps1', import.meta.url), 'utf8');
const packager = readFileSync(new URL('../scripts/package-desktop.ps1', import.meta.url), 'utf8');
const electronMain = readFileSync(new URL('../electron/main.cjs', import.meta.url), 'utf8');
const electronPreload = readFileSync(new URL('../electron/preload.cjs', import.meta.url), 'utf8');
const electronPackager = readFileSync(new URL('../scripts/package-electron.ps1', import.meta.url), 'utf8');
const packageJson = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'));
const localServer = readFileSync(new URL('../local-server.py', import.meta.url), 'utf8');
const readme = readFileSync(new URL('../README.md', import.meta.url), 'utf8');

assert.match(launcher, /\$distIndex/);
assert.match(launcher, /Built frontend not found and Vite is unavailable/);
assert.match(launcher, /local-server\.py/);
assert.match(launcher, /--app=\$url/);
assert.match(launcher, /Microsoft\\Edge\\Application\\msedge\.exe/);
assert.match(shortcut, /Codex Quota Glance\.lnk/);
assert.match(shortcut, /start-desktop\.ps1/);
assert.match(packager, /release/);
assert.match(packager, /Codex Quota Glance\.cmd/);
assert.match(packager, /includesUserData = \$false/);
assert.doesNotMatch(packager, /'data'/);
assert.match(readme, /npm run desktop/);
assert.match(readme, /npm run install-shortcut/);
assert.match(readme, /npm run package-desktop/);
assert.match(readme, /does not include `data\\`/);
assert.match(readme, /uncachedInputTokens = max\(0, inputTokens - cachedInputTokens\)/);

assert.equal(packageJson.main, 'electron/main.cjs');
assert.match(packageJson.scripts.electron, /electron \./);
assert.match(packageJson.scripts['package-electron'], /package-electron\.ps1/);
assert.match(electronMain, /BrowserWindow/);
assert.match(electronMain, /Tray/);
assert.match(electronMain, /setAppUserModelId\(APP_USER_MODEL_ID\)/);
assert.match(electronMain, /\\u663e\\u793a\/\\u9690\\u85cf\\u80f6\\u56ca/);
assert.match(electronMain, /icon\.ico/);
assert.match(electronMain, /frame:\s*false/);
assert.match(electronMain, /transparent:\s*true/);
assert.match(electronMain, /skipTaskbar:\s*true/);
assert.match(electronMain, /alwaysOnTop:\s*true/);
assert.match(electronMain, /openSettingsWindow/);
assert.match(electronMain, /desktop=1/);
assert.match(electronMain, /DEFAULT_CAPSULE_SIZE/);
assert.match(electronMain, /DEFAULT_CAPSULE_SIZE\s*=\s*\{\s*width:\s*620,\s*height:\s*72\s*\}/);
assert.match(electronMain, /DEFAULT_DETAIL_SIZE/);
assert.match(electronMain, /WINDOW_MARGIN/);
assert.match(electronMain, /desktop-detail-open/);
assert.match(electronMain, /desktop-layout-update/);
assert.match(electronMain, /desktop-toast-open/);
assert.match(electronMain, /RESERVED_TOAST_SPACE/);
assert.match(electronMain, /setCapsuleWindowBounds/);
assert.match(electronPreload, /setToastOpen/);
assert.match(electronMain, /desktop-popover-placement/);
assert.match(electronMain, /resizeCapsuleWindow/);
assert.match(electronMain, /normalizeLayout/);
assert.match(electronMain, /capsuleAnchor/);
assert.doesNotMatch(electronMain, /view=detail/);
assert.doesNotMatch(electronMain, /CAPSULE_EXPANDED_SIZE/);
assert.match(electronMain, /keepFloatingWindowOnTop/);
assert.match(electronMain, /moveTop\(\)/);
assert.match(electronMain, /createTrayImage/);
assert.match(electronMain, /local-server\.exe/);
assert.match(electronMain, /local-server\.py/);
assert.match(electronMain, /CODEX_QUOTA_APP_ROOT/);
assert.match(electronMain, /127\.0\.0\.1/);
assert.match(electronMain, /before-quit/);
assert.match(electronPackager, /PyInstaller/);
assert.match(electronPackager, /local-server\.exe/);
assert.match(electronPackager, /electron-packager/);
assert.match(electronPackager, /--asar=false/);
assert.match(electronPackager, /--icon=electron\\icon\.ico/);
assert.match(electronPackager, /release-electron/);
assert.match(electronPackager, /Codex Quota Glance\.exe/);
assert.match(electronPackager, /CodexQuotaGlance-win32-x64\.zip/);
assert.match(localServer, /LOCALAPPDATA/);
assert.match(localServer, /CODEX_QUOTA_DIST_DIR/);
assert.match(localServer, /getattr\(sys, "frozen", False\)/);
assert.match(readme, /npm run package-electron/);
assert.match(readme, /release-electron\\Codex Quota Glance-win32-x64\\Codex Quota Glance\.exe/);

console.log('desktop launcher tests passed');
