import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const electronMain = readFileSync(new URL('../electron/main.cjs', import.meta.url), 'utf8');
const electronPreload = readFileSync(new URL('../electron/preload.cjs', import.meta.url), 'utf8');
const backend = readFileSync(new URL('../electron/local-backend.cjs', import.meta.url), 'utf8');
const packageJson = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'));
const readme = readFileSync(new URL('../README.md', import.meta.url), 'utf8');

assert.equal(packageJson.main, 'electron/main.cjs');
assert.match(packageJson.scripts.electron, /electron \./);
assert.equal(packageJson.scripts.dist, 'node scripts/clean-generated.mjs && vite build && electron-builder --win');
assert.equal(packageJson.scripts['dist:win'], 'node scripts/clean-generated.mjs && vite build && electron-builder --win');
assert.equal(packageJson.build.asar, true);
assert.equal(packageJson.scripts.desktop, undefined);
assert.equal(packageJson.scripts['package-electron'], undefined);
assert.equal(packageJson.scripts['package-desktop'], undefined);
assert.equal(packageJson.scripts['install-shortcut'], undefined);
assert.equal(packageJson.build.directories.output, 'dist-electron');

assert.match(electronMain, /BrowserWindow/);
assert.match(electronMain, /Tray/);
assert.match(electronMain, /setAppUserModelId\(APP_USER_MODEL_ID\)/);
assert.match(electronMain, /\\u663e\\u793a\/\\u9690\\u85cf\\u80f6\\u56ca/);
assert.match(electronMain, /icon\.ico/);
assert.match(electronMain, /frame:\s*false/);
assert.match(electronMain, /transparent:\s*true/);
assert.match(electronMain, /skipTaskbar:\s*true/);
assert.match(electronMain, /alwaysOnTop:\s*true/);
assert.match(electronMain, /openSettingsWindow/);
assert.match(electronMain, /desktop=1/);
assert.match(electronMain, /DEFAULT_CAPSULE_SIZE\s*=\s*\{\s*width:\s*620,\s*height:\s*72\s*\}/);
assert.match(electronMain, /DEFAULT_DETAIL_SIZE/);
assert.match(electronMain, /WINDOW_MARGIN/);
assert.match(electronMain, /desktop-detail-open/);
assert.match(electronMain, /desktop-layout-update/);
assert.match(electronMain, /desktop-toast-open/);
assert.match(electronMain, /RESERVED_TOAST_SPACE/);
assert.match(electronMain, /setCapsuleWindowBounds/);
assert.match(electronPreload, /setToastOpen/);
assert.match(electronMain, /desktop-popover-placement/);
assert.match(electronMain, /resizeCapsuleWindow/);
assert.match(electronMain, /normalizeLayout/);
assert.match(electronMain, /capsuleAnchor/);
assert.match(electronMain, /keepFloatingWindowOnTop/);
assert.match(electronMain, /moveTop\(\)/);
assert.match(electronMain, /createTrayImage/);
assert.match(electronMain, /startLocalBackend/);
assert.match(electronMain, /app\.getAppPath\(\)/);
assert.match(backend, /startLocalBackend/);
assert.match(backend, /CodexQuotaGlance/);
assert.doesNotMatch(electronMain, /view=detail/);
assert.doesNotMatch(electronMain, /CAPSULE_EXPANDED_SIZE/);
assert.doesNotMatch(electronMain, /local-server\.py/);
assert.doesNotMatch(electronMain, /local-server\.exe/);
assert.doesNotMatch(readme, /npm run package-electron/);
assert.match(readme, /npm run dist:win/);
assert.match(readme, /dist-electron\\CodexQuotaGlance-<version>-win-x64\.exe/);

console.log('desktop launcher tests passed');
