import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const backendSource = readFileSync(new URL('../electron/local-backend.cjs', import.meta.url), 'utf8');
const mainSource = readFileSync(new URL('../electron/main.cjs', import.meta.url), 'utf8');
const packageJson = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'));

assert.match(backendSource, /require\('node:sqlite'\)/);
assert.match(backendSource, /create table if not exists newapi_logs/);
assert.match(backendSource, /create table if not exists codex_token_events/);
assert.match(backendSource, /create table if not exists codex_runtime_state/);
assert.match(backendSource, /function readCodexRuntimeState/);
assert.match(backendSource, /function writeCodexRuntimeState/);
assert.match(backendSource, /syncTodayCodexTokenEvents/);
assert.match(backendSource, /for \(const rawEvent of newEvents\)[\s\S]*saveCodexTokenEvent/);
assert.match(backendSource, /function getLatestCodexEventAt\(\)/);
assert.match(backendSource, /today:\s*summarizeCodexTokenRows\('where event_timestamp >= \?/);
assert.match(backendSource, /apiSpendToday:\s*summarizeCodexTokenRows/);
assert.match(backendSource, /const codexActivityCache/);
assert.match(backendSource, /CODEX_SESSION_DISCOVERY_TTL_SECONDS = 5/);
assert.match(backendSource, /CODEX_RATE_LIMIT_CACHE_TTL_SECONDS = 60/);
assert.doesNotMatch(backendSource, /lastUsageFingerprint/);
assert.doesNotMatch(backendSource, /lag\(input_tokens\) over/);
assert.match(backendSource, /from codex_token_events\s+\$\{whereSql\}/);
assert.match(backendSource, /\/local-api\/health/);
assert.match(backendSource, /electron-local-backend/);
assert.match(backendSource, /\/local-api\/newapi\/logs\/summary/);
assert.match(backendSource, /\/local-api\/newapi\/logs\/sync/);
assert.match(backendSource, /\/local-api\/codex\/token\/latest/);
assert.match(backendSource, /\/local-api\/codex\/overview/);
assert.match(backendSource, /\/local-api\/codex\/quota-reminder\/confirm/);
assert.match(backendSource, /isQuotaReminderPending/);
assert.match(backendSource, /confirmQuotaReminder/);
assert.match(backendSource, /\/local-api\/codex\/status/);
assert.match(backendSource, /function startCodexSessionWatcher/);
assert.match(backendSource, /fs\.watch\(\s*paths\.codexSessions/);
assert.match(backendSource, /recursive:\s*process\.platform === 'win32'/);
assert.match(backendSource, /CODEX_SESSION_WATCH_DEBOUNCE_MS = 100/);
assert.match(backendSource, /function stopCodexSessionWatcher/);
assert.match(backendSource, /codexSessionWatcher\.close\(\)/);
assert.match(backendSource, /onCodexSessionChanged/);
assert.match(backendSource, /let codexSessionWatchNeedsDiscovery = false/);
assert.match(backendSource, /isSameFilePath\(changedPath, codexSessionCache\.path\)/);
assert.match(backendSource, /if \(codexSessionWatchNeedsDiscovery\)/);
assert.match(backendSource, /\/local-api\/update\/latest/);
assert.match(backendSource, /GITHUB_LATEST_RELEASE_URL/);
assert.match(backendSource, /Authorization: `Bearer/);
assert.match(backendSource, /New-Api-User/);
assert.match(backendSource, /account\/rateLimits\/read/);
assert.match(mainSource, /startLocalBackend/);
assert.match(mainSource, /stopLocalBackend/);
assert.doesNotMatch(mainSource, /local-server\.py/);
assert.doesNotMatch(mainSource, /local-server\.exe/);
assert.doesNotMatch(mainSource, /spawn\(backend\.command/);
assert.equal(packageJson.scripts['dist:win'], 'node scripts/clean-generated.mjs && vite build && electron-builder --win');
assert.equal(packageJson.scripts['build:sidecar'], undefined);
assert.equal(packageJson.build.files.includes('local-server.exe'), false);

console.log('local backend source tests passed');
