import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const css = readFileSync(new URL('../src/styles.css', import.meta.url), 'utf8');

assert.match(css, /\.floating-capsule\s*{[\s\S]*width:\s*min\(440px, calc\(100vw - 32px\)\);/);
assert.match(css, /\.floating-capsule\s*{[\s\S]*min-height:\s*106px;/);
assert.match(css, /\.floating-capsule\s*{[\s\S]*grid-template-areas:/);
assert.match(css, /\.draggable-capsule\s*{[\s\S]*position:\s*fixed;/);
assert.match(css, /\.draggable-capsule\s*{[\s\S]*z-index:\s*20;/);
assert.match(css, /\.draggable-capsule\s*{[\s\S]*touch-action:\s*none;/);
assert.match(css, /\.draggable-capsule:active\s*{[\s\S]*cursor:\s*grabbing;/);
assert.match(css, /body:has\(\.draggable-capsule\[data-desktop-shell="true"\]\)\s*{[\s\S]*overflow:\s*hidden;/);
assert.match(css, /\.app-shell:has\(\.draggable-capsule\[data-desktop-shell="true"\]\)\s*{[\s\S]*min-height:\s*0;/);
assert.match(css, /\.field-error\s*{/);
assert.match(css, /input\[aria-invalid="true"\]\s*{/);
assert.match(css, /\.secret-input\s*{/);
assert.match(css, /\.icon-button\s*{/);
assert.match(css, /\.settings-actions\s*{/);
assert.match(css, /\.primary-action\s*{/);
assert.match(css, /\.secondary-action\s*{/);
assert.match(css, /\.connection-message\s*{/);
assert.match(css, /\.capsule-stack\s*{[\s\S]*padding-top:\s*0;/);
assert.match(css, /\.spend-toast\s*{[\s\S]*width:\s*calc\(100% - 34px\);/);
assert.match(css, /\.spend-toast\s*{[\s\S]*bottom:\s*calc\(100% - 1px\);/);
assert.match(css, /\.spend-toast\s*{[\s\S]*height:\s*24px;/);
assert.match(css, /\.spend-toast\s*{[\s\S]*border-radius:\s*13px 13px 0 0;/);
assert.match(css, /\.spend-toast\s*{[\s\S]*font-size:\s*10px;/);
assert.match(css, /\.spend-toast\s*{[\s\S]*z-index:\s*0;/);
assert.match(css, /\.spend-toast\s*{[\s\S]*clip-path:\s*inset/);
assert.match(css, /@keyframes spend-toast-rise/);
assert.match(css, /clip-path:\s*inset\(100% 0 0 0/);
assert.match(css, /\.spend-toast-main\s*{[\s\S]*white-space:\s*nowrap;/);
assert.match(css, /\.floating-capsule\s*{[\s\S]*z-index:\s*1;/);
assert.match(css, /\.capsule-popover\s*{[\s\S]*width:\s*min\(520px,\s*calc\(100vw - 32px\)\);/);
assert.match(css, /\.capsule-popover\s*{[\s\S]*overflow:\s*visible;/);
assert.match(css, /\.draggable-capsule\[data-desktop-shell="true"\] \.capsule-stack\s*{[\s\S]*padding-top:\s*0;/);
assert.doesNotMatch(css, /padding-top:\s*328px;/);
assert.match(css, /\.draggable-capsule\[data-desktop-shell="true"\] \.capsule-popover\s*{[\s\S]*width:\s*520px;/);
assert.match(css, /\.capsule-popover\.is-detached-detail\s*{[\s\S]*animation:\s*none;/);
assert.match(css, /\.capsule-popover\.is-detached-detail\s*{[\s\S]*opacity:\s*1;/);
assert.match(css, /\.draggable-capsule\[data-desktop-shell="true"\]\[data-layout-ready="false"\] \.capsule-popover\s*{[\s\S]*opacity:\s*0;/);
assert.match(css, /@keyframes popover-slide-up/);
assert.match(css, /@keyframes popover-slide-down/);
assert.match(css, /\.draggable-capsule\[data-desktop-shell="true"\]\s*{[\s\S]*max-width:\s*none;/);
assert.match(css, /\.draggable-capsule\[data-desktop-shell="true"\] \.floating-capsule\s*{[\s\S]*max-width:\s*none;/);
assert.match(css, /\.capsule-popover \.section-band\s*{[\s\S]*padding:\s*10px;/);
assert.match(css, /\.capsule-popover dl\s*{[\s\S]*font-size:\s*11\.5px;/);
assert.match(css, /\.capsule-popover dl\s*{[\s\S]*gap:\s*4px 8px;/);
assert.match(css, /\.detail-metrics-grid\s*{[\s\S]*grid-template-columns:/);
assert.match(css, /\.traffic-close\.is-active\s*{[\s\S]*rgba\(255,\s*95,\s*87,\s*0\.68\)/);
assert.match(css, /\.traffic-minimize\.is-active\s*{[\s\S]*rgba\(255,\s*189,\s*46,\s*0\.7\)/);
assert.match(css, /\.traffic-ok\.is-active\s*{[\s\S]*rgba\(40,\s*200,\s*64,\s*0\.66\)/);
assert.match(css, /@keyframes signal-breathe\s*{[\s\S]*0 0 20px currentColor/);
assert.match(css, /\.theme-toggle\s*{/);
assert.match(css, /\[data-theme="light"\]\s+\.floating-capsule/);
assert.match(css, /\[data-theme="dark"\]\.settings-window-shell/);
assert.match(css, /\[data-theme="dark"\]\.detail-window-shell/);
assert.match(css, /\.draggable-capsule\[data-popover-placement="top"\]\s+\.capsule-popover\s*{[\s\S]*bottom:\s*calc\(100% \+ 8px\);/);
assert.match(css, /\.draggable-capsule\[data-desktop-shell="true"\]\[data-popover-placement="top"\]\s*{[\s\S]*top:\s*0;/);

console.log('style tests passed');
